<a href="https://colab.research.google.com/github/LaxmiSahithiNagarapu/5810-Group-4/blob/main/nagarapu_In_class_exercise_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The second In-class-exercise (02/07/2023, 40 points in total)

The purpose of this exercise is to understand users' information needs, then collect data from different sources for analysis.

Question 1 (10 points): Describe an interesting research question (or practical question) you have in mind, what kind of data should be collected to answer the question(s)? How many data needed for the analysis? The detail steps for collecting and save the data.

In [1]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Idea: Analyze the movie rating and deliver patterns in the imdb site.

Data to be collected: collect the movie names, genre, rank, rating, description, year etc


Number of data needed: To analyze the data and identify patterns over it, we need large amount of data.

Steps for collecting and saving the data:

1. Find the movies' URLs on the imdb website. Use a web scraper to retrieve the movie's name, rating, year, description, and genre from the HTML of the webpage.

2. Clean the data in order to avoid of extra spaces.

4. Create a .csv file with columns for the title, rating, release year, synopsis, and genre, and save the data.

5.Use data analysis techniques to examine the gathered information, such as examining how movies are released or which genres have high ratings.

'''

"\nIdea: Analyze the movie rating and deliver patterns in the imdb site.\n\nData to be collected: collect the movie names, genre, rank, rating, description, year etc\n\n\nNumber of data needed: To analyze the data and identify patterns over it, we need large amount of data.\n\nSteps for collecting and saving the data:\n\n1. Find the movies' URLs on the imdb website. Use a web scraper to retrieve the movie's name, rating, year, description, and genre from the HTML of the webpage.\n\n2. Clean the data in order to avoid of extra spaces.\n\n4. Create a .csv file with columns for the title, rating, release year, synopsis, and genre, and save the data.\n\n5.Use data analysis techniques to examine the gathered information, such as examining how movies are released or which genres have high ratings.\n\n"

Question 2 (10 points): Write python code to collect 1000 data samples you discussed above.

In [13]:
# You code here (Please add comments in the code):

from bs4 import BeautifulSoup
import requests
import pandas as pd

data = {
    'rank': [],
    'name': [],
    'year': [],
    'runtime': [],
    'genre': [],
    'rating': [],
    'description': [],
    
}

In [24]:


root_url = 'https://www.imdb.com/'


url = 'https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=1'


def get_page_soup_data(url):
    r = requests.get(url)
    soup = BeautifulSoup(r.content, 'html.parser')
    return soup

def get_next_page_url(soup):
    pages_data = soup.find('div', class_='desc')
    if soup.find('div', class_='desc').find('a', class_='lister-page-next next-page'):
        nexturl = root_url + str(soup.find('div', class_='desc').find('a', class_='lister-page-next next-page')['href'])
        return nexturl
    else:
        return

while True:
   
    soup = get_page_soup_data(url)
    
   
    movielist = soup.find('div', class_='lister-list').find_all('div', class_='lister-item mode-advanced')
    
    
    for movie in movielist:
        name = movie.find('h3', class_ = 'lister-item-header').a.text.strip()
        rank = movie.find('h3', class_='lister-item-header').text.split('.')[0].strip()
        year = movie.find('h3', class_='lister-item-header').find('span', class_='lister-item-year text-muted unbold').text.strip('()')

        runtime = movie.find_all('p', class_='text-muted')[0].find('span', class_='runtime').text.strip()
        genre  = movie.find_all('p', class_='text-muted')[0].find('span', class_='genre').text.strip()
        rating = movie.find('div', class_='inline-block ratings-imdb-rating').text.strip()
        description = movie.find_all('p', class_='text-muted')[1].text.strip()

        data['rank'].append(rank)
        data['name'].append(name)
        data['year'].append(year)
        data['runtime'].append(runtime)
        data['genre'].append(genre)
        data['rating'].append(rating)
        data['description'].append(description)
        
    

    url = get_next_page_url(soup)

    print("Next URL: ", url)
    print("Data collected till previous url: ", len(data['rank']))

    
    if not url:
        break

Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=51
Data collected till previous url:  13050
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=101
Data collected till previous url:  13100
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=151
Data collected till previous url:  13150
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=201
Data collected till previous url:  13200
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=251
Data collected till previous url:  13250
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=301
Data collected till previous url:  13300
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=351
Data collected till previous url:  13350
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=401
Data collected till previous url:  13400
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=451
Data collected till previous url:  13450
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=501
Data collected till previous url:  13500
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=551
Data collected till previous url:  13550
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=601
Data collected till previous url:  13600
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=651
Data collected till previous url:  13650
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=701
Data collected till previous url:  13700
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=751
Data collected till previous url:  13750
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=801
Data collected till previous url:  13800
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=851
Data collected till previous url:  13850
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=901
Data collected till previous url:  13900
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=951
Data collected till previous url:  13950
Next URL:  None
Data collected till previous url:  14000

In [14]:
df = pd.DataFrame(data)
df.shape

(0, 7)

In [15]:
df.tail()

Empty DataFrame
Columns: [rank, name, year, runtime, genre, rating, description]
Index: []

Question 3 (10 points): Write python code to collect 1000 articles from Google Scholar (https://scholar.google.com/), Microsoft Academic (https://academic.microsoft.com/home), or CiteSeerX (https://citeseerx.ist.psu.edu/index), or Semantic Scholar (https://www.semanticscholar.org/), or ACM Digital Libraries (https://dl.acm.org/) with the keyword "information retrieval". The articles should be published in the last 10 years (2012-2022).

The following information of the article needs to be collected:

(1) Title

(2) Venue/journal/conference being published

(3) Year

(4) Authors

(5) Abstract

In [6]:
# You code here (Please add comments in the code):




import pandas as pd
import requests
import json


topic = 'information retrieval'


frames = []

for offset in range(0, 1000, 100):
    url = f"https://api.semanticscholar.org/graph/v1/paper/search?query={topic}&offset={offset}&limit=100&fields=url,title,venue,year,authors,abstract"

    payload={}
    headers = {}
    
    
    response = requests.request("GET", url, headers=headers, data=payload)
    
    data = json.loads(response.text)['data']


    df = pd.DataFrame(data)
    
   
    frames.append(df) 


main_df = pd.concat(frames)

main_df.reset_index(drop=True)

,paperId,url,title,abstract,venue,year,authors
0,5f3b50c6c826ad105163b09d53e1eb498a4b3994,https://www.semanticscholar.org/paper/5f3b50c6...,Introduction to Information Retrieval,Introduction To Information Retrieval Overdriv...,J. Assoc. Inf. Sci. Technol.,2010.0,"[{'authorId': '1803434', 'name': 'R. Larson'}]"
1,807600ef43073cd9c59d4208ee710e90cf14efa8,https://www.semanticscholar.org/paper/807600ef...,BEIR: A Heterogenous Benchmark for Zero-shot E...,Existing neural information retrieval (IR) mod...,NeurIPS Datasets and Benchmarks,2021.0,"[{'authorId': '47583894', 'name': 'Nandan Thak..."
2,806c2c4327a31fded64a5d673ab82b133194c234,https://www.semanticscholar.org/paper/806c2c43...,Introduction to information retrieval,"Class-tested and coherent, this textbook teach...",,2008.0,"[{'authorId': '144783904', 'name': 'Christophe..."
3,49af3e80343eb80c61e727ae0c27541628c7c5e2,https://www.semanticscholar.org/paper/49af3e80...,Introduction to Modern Information Retrieval,Some people may be laughing when looking at yo...,,1983.0,"[{'authorId': '1797808', 'name': 'G. Salton'},..."
4,72c58a58ba1684dc8337c8e64e0b5dacfc94499e,https://www.semanticscholar.org/paper/72c58a58...,Information Retrieval,None,Lecture Notes in Computer Science,2018.0,"[{'authorId': '32293755', 'name': 'A. Dekhtyar'}]"
...,...,...,...,...,...,...,...
995,3f900d6782152e3fe2ecb8f6d9bb12879dacf6e4,https://www.semanticscholar.org/paper/3f900d67...,Case-Based User Profiling for Content Personal...,None,International Conference on Adaptive Hypermedi...,2000.0,"[{'authorId': '144372969', 'name': 'Keith Brad..."
996,a504bfdcaace7cccdc1dde453a5df8a359418e76,https://www.semanticscholar.org/paper/a504bfdc...,Ecphoric processes in episodic memory,Ecphory is a process by which retrieval inform...,,1983.0,"[{'authorId': '2083280287', 'name': 'Endel Tul..."
997,228029e7533e32a025071e31e3f4f08d2bea5f5a,https://www.semanticscholar.org/paper/228029e7...,Automatic image annotation and retrieval using...,Libraries have traditionally used manual image...,Annual International ACM SIGIR Conference on R...,2003.0,"[{'authorId': '1791802', 'name': 'J. Jeon'}, {..."
998,628f503da12fd3f385cff7ea64d6d6f97060cb4f,https://www.semanticscholar.org/paper/628f503d...,Statistically optimized inversion algorithm fo...,Abstract. The proposed development is an attem...,,2010.0,"[{'authorId': '143945203', 'name': 'O. Dubovik..."
999,a157969d1722840355a3296dbc598d3d134668d6,https://www.semanticscholar.org/paper/a157969d...,"Semantic Annotation, Indexing, and Retrieval",None,International Workshop on the Semantic Web,2003.0,"[{'authorId': '3120224', 'name': 'A. Kiryakov'..."

In [7]:
main_df.shape

(1000, 7)

Question 4 (10 points): Write python code to collect 1000 posts from Twitter, or Facebook, or Instagram. You can either use hashtags, keywords, user_name, user_id, or other information to collect the data. 

The following information needs to be collected:

(1) User_name

(2) Posted time

(3) Text

In [10]:
# You code here (Please add comments in the code):

import pandas as pd
import numpy as np
import tweepy
from tweepy import OAuthHandler
import requests
import json



consumer_secret = "sVbJzekKuiAgq83Y7gCwNVbSowqQokGVzWexKHl2cXIPceWtSd"
access_token_secret = "oydIGymn9bS767FVEMawE9GyGAnMmBJfaY2XXKmHnmliF"
consumer_key ="2Em7SxlX9jPMfL4x97r3zMO0x"
access_token ="1439767876962029572-uUMt8oWRyzj9ilE5zk4uYbL93sCMPT"

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api_auth = tweepy.API(auth,wait_on_rate_limit=True)
user_name =str(input("Enter the user name\n"))


tweepy_cursor = tweepy.Cursor(api_auth.user_timeline, id=user_name).items(1000)

tweets_list = [[user_name ,tweet.created_at, tweet.text] for tweet in tweepy_cursor]

tweets_df = pd.DataFrame(tweets_list)
tweets_df.columns=['user_name','posted time','text']
tweets_df

Enter the user name
tim_cook

,user_name,posted time,text
0,tim_cook,2023-02-16 20:15:21,"Congratulations, @raye, on your wonderful debu..."
1,tim_cook,2023-02-14 16:52:40,Happy Valentine’s Day from all of us at Apple.
2,tim_cook,2023-02-13 03:38:36,"What a game! Congratulations, Kansas City!"
3,tim_cook,2023-02-13 02:37:35,One of the greats! Amazing show from @Rihanna....
4,tim_cook,2023-02-12 16:05:28,I loved spending part of Super Bowl weekend wi...
...,...,...,...
995,tim_cook,2017-12-12 12:39:42,A very happy #Hanukkah to everyone celebrating...
996,tim_cook,2017-12-10 18:54:47,"Beyond the urgent, never-ending work of protec..."
997,tim_cook,2017-12-09 20:37:07,Thanks to the Apple team for our biggest @Toys...
998,tim_cook,2017-12-09 02:05:05,A huge thanks @gwenstefani for celebrating the...
999,tim_cook,2017-12-08 02:53:03,Imagination and creativity drives us at Apple....